// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://arjhmbofqelqlyncfkoq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFyamhtYm9mcWVscWx5bmNma29xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk2Mjk4NjMsImV4cCI6MjA4NTIwNTg2M30.Tjwvxiseuz9EiuOhsYWK7ilh0AJLUwbFudh7lWp5SiQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});