// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibzwbzruhfecnilkmgon.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImliendienJ1aGZlY25pbGttZ29uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NjU2NzIsImV4cCI6MjA3MjM0MTY3Mn0.Bum180392TsDOoMrnH5aTTN8rzAt5GQ6HPAkGm8u-yk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});